### PR TITLE
Update plato to 1.7.0 to allow ES6

### PR DESCRIPTION
**Pull request by nickydonna**

### CODE REVIEW

**Comment by kevde** [comment]
Latest version of Plato already supports ES6. Check it out on https://github.com/es-analysis/plato. I will try to contact @jsoverson to include them in the master branch

**Comment by donnanicolas** [comment]
yes, this PR update the dependencies for grunt plato and add options for eslint

**Comment by kevde** [comment]
Thanks @jsoverson. Have tried the patches effective on ES6 codes

**Comment by nickydonna** [comment]
@jsoverson would like to give me access to editing to maintain this repository?

**Pull request merged**
